MOUSEKEY_ENABLE = no     # Mouse keys
RGBLIGHT_ENABLE = no     # Enable WS2812 RGB underlight.
RGB_MATRIX_ENABLE = yes
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
WPM_ENABLE      = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
